[2025-07-17T06:44:54.813+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quant_backtest.run_backtester scheduled__2023-07-28T00:00:00+00:00 [queued]>
[2025-07-17T06:44:54.818+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quant_backtest.run_backtester scheduled__2023-07-28T00:00:00+00:00 [queued]>
[2025-07-17T06:44:54.818+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-07-17T06:44:54.827+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_backtester> on 2023-07-28 00:00:00+00:00
[2025-07-17T06:44:54.830+0000] {standard_task_runner.py:57} INFO - Started process 225 to run task
[2025-07-17T06:44:54.832+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'quant_backtest', 'run_backtester', 'scheduled__2023-07-28T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/quant_backtest.py', '--cfg-path', '/tmp/tmpbx_nphpk']
[2025-07-17T06:44:54.833+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask run_backtester
[2025-07-17T06:44:54.865+0000] {task_command.py:410} INFO - Running <TaskInstance: quant_backtest.run_backtester scheduled__2023-07-28T00:00:00+00:00 [running]> on host 24ebc2bdd9e4
[2025-07-17T06:44:54.928+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='quant_backtest' AIRFLOW_CTX_TASK_ID='run_backtester' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-28T00:00:00+00:00'
[2025-07-17T06:44:54.928+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-17T06:44:54.929+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/airflow/backtester/backtest.py']
[2025-07-17T06:44:54.934+0000] {subprocess.py:86} INFO - Output:
[2025-07-17T06:44:55.760+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-17T06:44:55.761+0000] {subprocess.py:93} INFO -   File "/opt/airflow/backtester/backtest.py", line 25, in <module>
[2025-07-17T06:44:55.761+0000] {subprocess.py:93} INFO -     raw_bars  = fetch_agg_bars('AAPL', start_iso, end_iso)
[2025-07-17T06:44:55.761+0000] {subprocess.py:93} INFO -   File "/opt/airflow/data_ingestion/ingestion.py", line 28, in fetch_agg_bars
[2025-07-17T06:44:55.762+0000] {subprocess.py:93} INFO -     r.raise_for_status()
[2025-07-17T06:44:55.762+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
[2025-07-17T06:44:55.764+0000] {subprocess.py:93} INFO -     raise HTTPError(http_error_msg, response=self)
[2025-07-17T06:44:55.765+0000] {subprocess.py:93} INFO - requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2023-01-01/2025-01-01?adjusted=true&sort=asc&limit=5000&apiKey=XbTx7h_kP0dGxI8fdRCC7Blx9i0Wjr3l
[2025-07-17T06:44:55.845+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-17T06:44:55.855+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-17T06:44:55.857+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=quant_backtest, task_id=run_backtester, execution_date=20230728T000000, start_date=20250717T064454, end_date=20250717T064455
[2025-07-17T06:44:55.866+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 71 for task run_backtester (Bash command failed. The command returned a non-zero exit code 1.; 225)
[2025-07-17T06:44:55.879+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-17T06:44:55.891+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
